name: CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master

jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: yarn
      - name: build
        run: yarn build
      - name: test
        run: yarn test

  size:
    name: Compressed Size Action
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pattern: "**/dist/**/*.min.js"
